# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:47
from __future__ import unicode_literals

from django.db import migrations
import saleor.product.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20160218_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='protein',
            field=saleor.product.models.fields.WeightField(decimal_places=2, default=0.0, max_digits=6, unit='lb', verbose_name='weight'),
            preserve_default=False,
        ),
    ]
